### ISSUE TITLE
YamagiQ2 flatpak needs to be updated to v8.20.

### ISSUE THREAD

**Issue by Shockwave508** [flathub/org.yamagi.YamagiQ2#13]
Issue is self-explanatory.

**Comment by Eonfge** [comment]
I'll update the release notes: https://github.com/flathub/org.yamagi.YamagiQ2/pull/14

Do know that you can already run and use 8.2.0

**Comment by Eonfge** [comment]
Digging into it, I see the problem. The package changes were never flagged because of a bug with release-monitoring.org

I'll make sure to update the package properly. Thanks for letting me know
